from enum import Enum


class MessageTypes(Enum):
    NEW_TASK_BUNDLE = 1
    REQUEST_TASK_BUNDLE_TRANSFER = 2
    TASK_BUNDLE_TRANSFER = 3
    SWARM_MEMORY_OBJECT_LOCATION = 4
    REQUEST_SWARM_MEMORY_READ = 5
    TRANSFER_SWARM_MEMORY_VALUE = 6
    DELETE_FROM_SWARM_MEMORY = 7
    NOTIFY_TASK_BUNDLE_EXECUTION_START = 8
